import { X } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import type { Entry, EntryPatch } from '../../types/entries';

export function PropertiesDialog({ entry, onClose, onSubmit }: { entry: Entry; onClose: () => void; onSubmit: (patch: EntryPatch) => Promise<void> }) {
  const [description, setDescription] = useState(entry.description); const [sortOrder, setSortOrder] = useState(String(entry.sortOrder)); const [isPublic, setPublic] = useState(entry.isPublic); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { setDescription(entry.description); setSortOrder(String(entry.sortOrder)); setPublic(entry.isPublic); }, [entry]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await onSubmit({ description, sortOrder: Number(sortOrder) || 0, isPublic }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save properties.'); } finally { setBusy(false); } }
  return <div className="dialogBackdrop" onMouseDown={onClose}><section className="operationDialog" role="dialog" aria-modal="true" aria-label={`Properties for ${entry.name}`} onMouseDown={(event) => event.stopPropagation()}><div className="dialogHeader"><h2>Properties</h2><button className="iconButton" type="button" onClick={onClose} aria-label="Close"><X aria-hidden="true" size={17} /></button></div><form onSubmit={submit}><label>Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Sort order<input type="number" value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} /></label><label className="checkboxLabel"><input type="checkbox" checked={isPublic} onChange={(event) => setPublic(event.target.checked)} />Public</label>{error ? <p className="formError" role="alert">{error}</p> : null}<div className="dialogButtons"><button className="button" type="button" onClick={onClose}>Cancel</button><button className="button primary" type="submit" disabled={busy}>{busy ? 'Saving' : 'Save'}</button></div></form></section></div>;
}
